name: Terraform DEV Destroy & Apply

on:
  workflow_dispatch:

jobs:
  destroy-dev:
    name: Destroy DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init DEV
        working-directory: infra/envs/dev
        run: terraform init

      - name: Terraform Destroy DEV
        working-directory: infra/envs/dev
        run: terraform destroy -auto-approve

  apply-dev:
    name: Apply DEV
    runs-on: ubuntu-latest
    environment: dev
    needs: destroy-dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init DEV
        working-directory: infra/envs/dev
        run: terraform init

      - name: Terraform Apply DEV
        working-directory: infra/envs/dev
        run: terraform apply -auto-approve
