name: Terraform CI/CD DEV (apply / destroy)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Acción de Terraform a ejecutar"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-dev:
    name: Terraform DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init DEV
        working-directory: infra/envs/dev
        run: terraform init

      - name: Terraform Apply DEV
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: infra/envs/dev
        run: terraform apply -auto-approve

      - name: Terraform Destroy DEV
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: infra/envs/dev
        run: terraform destroy -auto-approve

