name: Terraform CI/CD con destroy en DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  destroy-dev:
    name: Destroy DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Descargar c√≥digo
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init DEV
        working-directory: infra/envs/dev
        run: terraform init

      - name: Terraform Destroy DEV
        working-directory: infra/envs/dev
        run: terraform destroy -auto-approve
