name: Terraform CI/CD Multi-Ambiente

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Acci√≥n de Terraform"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

      environment:
        description: "Ambiente a desplegar"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      # 1Ô∏è‚É£ Checkout
      - uses: actions/checkout@v4

      # 2Ô∏è‚É£ Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 3Ô∏è‚É£ AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4Ô∏è‚É£ Init
      - name: Terraform Init
        working-directory: infra/envs/${{ github.event.inputs.environment }}
        run: terraform init -reconfigure

      # ======================
      # üöÄ APPLY
      # ======================
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: infra/envs/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve

      # ======================
      # üí£ DESTROY (CORRECTO)
      # ======================
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: infra/envs/${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve
